djangocrud/urls.py
from django.contrib import admin
from django.urls import path
from tasks import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path("signup/", views.signup, name="signup"),
    path("tasks/", views.tasks, name="tasks"),
    path("tasks_completed/", views.tasks_completed, name="tasks_completed"),
    path("tasks/create/", views.create_task, name="create_task"),
    path("tasks/<int:task_id>/", views.task_detail, name="task_detail"),
    path("tasks/<int:task_id>/complete", views.complete_task, name="complete_task"),
    path("tasks/<int:task_id>/delete", views.delete_task, name="delete_task"),
    path("logout/", views.signout, name="logout"),
    path("signin/", views.signin, name="signin"),
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    datecompleted = models.DateTimeField(null=True, blank=True)
    important = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title + ' - by ' + self.user.username

tasks/forms.py
from django.forms import ModelForm
from .models import Task

class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'important']
        

tasks/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from .forms import TaskForm
from .models import Task
from django.utils import timezone
from django.contrib.auth.decorators import login_required


def home(request):
    return render(request, "home.html")


def signup(request):
    if request.method == "GET":
        return render(request, "signup.html", {"form": UserCreationForm})
    else:
        if request.POST["password1"] == request.POST["password2"]:
            try:
                user = User.objects.create_user(
                    username=request.POST["username"],
                    password=request.POST["password1"],
                )
                user.save()
                login(request, user)
                return redirect("tasks")
            except IntegrityError:
                return render(
                    request,
                    "signup.html",
                    {"form": UserCreationForm, "error": "Username already exists"},
                )
        return render(
            request,
            "signup.html",
            {"form": UserCreationForm, "error": "Password no not match"},
        )


@login_required
def tasks(request):
    tasks = Task.objects.filter(user=request.user, datecompleted__isnull=True)
    return render(request, "tasks.html", {"tasks": tasks})


@login_required
def tasks_completed(request):
    tasks = Task.objects.filter(
        user=request.user, datecompleted__isnull=False
    ).order_by("-datecompleted")
    return render(request, "tasks.html", {"tasks": tasks})


@login_required
def create_task(request):
    if request.method == "GET":
        return render(request, "create_task.html", {"form": TaskForm})
    else:
        try:
            form = TaskForm(request.POST)
            new_task = form.save(commit=False)
            new_task.user = request.user
            new_task.save()
            return redirect("tasks")
        except ValueError:
            return render(
                request,
                "create_task.html",
                {"form": TaskForm, "error": "Please provide valida data"},
            )


@login_required
def task_detail(request, task_id):
    if request.method == "GET":
        task = get_object_or_404(Task, pk=task_id, user=request.user)
        form = TaskForm(instance=task)
        return render(request, "task_detail.html", {"task": task, "form": form})
    else:
        try:
            task = get_object_or_404(Task, pk=task_id, user=request.user)
            form = TaskForm(request.POST, instance=task)
            form.save()
            return redirect("tasks")
        except ValueError:
            return render(
                request,
                "task_detail.html",
                {"task": task, "form": form, "error": "Error updating task"},
            )


@login_required
def complete_task(request, task_id):
    task = get_object_or_404(Task, pk=task_id, user=request.user)
    if request.method == "POST":
        task.datecompleted = timezone.now()
        task.save()
        return redirect("tasks")


@login_required
def delete_task(request, task_id):
    task = get_object_or_404(Task, pk=task_id, user=request.user)
    if request.method == "POST":
        task.datecompleted = timezone.now()
        task.delete()
        return redirect("tasks")


@login_required
def signout(request):
    logout(request)
    return redirect("home")


def signin(request):
    if request.method == "GET":
        return render(request, "signin.html", {"form": AuthenticationForm})
    else:
        user = authenticate(
            request,
            username=request.POST["username"],
            password=request.POST["password"],
        )
        if user is None:
            return render(
                request,
                "signin.html",
                {
                    "form": AuthenticationForm,
                    "error": "Username or password is incorrect",
                },
            )
        else:
            login(request, user)
            return redirect("tasks")

tasks/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Soelco</title>
</head>
<style>
    @import url('https://fonts.googleapis.com/css2?family=Roboto&display=swap');


    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    body {
        font-family: 'Roboto', sans-serif;
        min-height: 100vh;
        color: white;
    }

    .container {
        max-width: 1200px;
        width: 90%;
        margin: auto;
    }

    .nav__promo {
        min-height: 40px;
        display: flex;
        justify-content: center;
        background: #054A91;
        align-items: center;
        text-align: center;
        font-size: 14px;
        padding: 0 10px;
    }

    .nav {
        position: fixed;
        width: 100%;
        background: #ffffffe8;
    }

    .nav__content {
        min-height: 90px;
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

    .nav__logo {
        max-width: 280px;
        height: 100%;
        width: 70%;
        object-fit: contain;
    }

    .nav__links {
        display: none;
    }

    .nav__links.active {
        display: flex;
        flex-direction: column;
        background-color: #054A91;
        position: absolute;
        top: 100%;
        left: 0;
        width: 100%;
        padding: 20px 5px;
    }

    .nav__links a {
        color: #ffffff;
        padding: 10px;
        text-decoration: none;
        font-weight: 600;
        font-size: 18px;
    }

    .burger {
        cursor: pointer;
        display: block;
    }

    .line1,
    .line2,
    .line3 {
        width: 25px;
        height: 3px;
        background-color: #000000;
        margin: 5px;
    }

    @media screen and (min-width: 768px) {
        .nav__promo {
            font-size: 18px;
        }
    }

    @media screen and (min-width: 1200px) {
        .burger {
            display: none;
        }

        .nav__links {
            display: flex;
        }

        .nav__links.active {
            display: none;
        }

        .nav__links a {
            color: #013D88;
        }
    }

    .form-control {
        background-color: red;
    }
</style>

<body>

    <nav class="nav">
        <div class="nav__promo">
            <p>¡Encuentra en nuestras tiendas una solucion de financiamiento para llever tus productos del hogar!</p>
        </div>
        <div class="nav__content container">

            <img class="nav__logo" src="{% static 'img/logo.png' %}" alt="logo">

            <ul class="nav__links">
                <a href="/">Home</a>
                {% if user.is_authenticated %}
                <a href="/tasks">Productos</a>
                <a href="/tasks_completed">Productos Vendidos</a>
                <a href="/tasks/create">Crear Producto</a>
                <a href="/logout">Logout</a>
                {% else %}
                <a href="/signup">Regristrarse</a>
                <a href="/signin">Iniciar Sesion</a>
                {% endif %}
            </ul>

            <div class="burger" onclick="toggleMenu()">
                <div class="line1"></div>
                <div class="line2"></div>
                <div class="line3"></div>
            </div>
        </div>


    </nav>


    {% if "tasks_completed" in request.path %}
    <h1 class="lista__title">Productos Vendidos</h1>
    {% else %}
    <h1 class="lista__title">Producto en venta</h1>
    {% endif %}

    {% block content %}
    {% endblock %}

</body>

</html>



<script>
    function toggleMenu() {
        let navLinks = document.querySelector('.nav__links');
        navLinks.classList.toggle('active');
    }

    // Agregar un evento clic a cada enlace del menú desplegable para cerrar el menú después de hacer clic en uno de ellos
    var links = document.querySelectorAll('.nav__links a');
    links.forEach(function (link) {
        link.addEventListener('click', function () {
            let navLinks = document.querySelector('.nav__links');
            navLinks.classList.remove('active');
        });
    });

</script>

tasks/templates/create_task.html
<style>
    .form__container {
        min-height: 900px;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }

    .form {
        max-width: 350px;
        width: 90%;
        color: black;
        background: white;
        border-radius: 12px;
        display: flex;
        flex-direction: column;
        text-align: center;
        padding: 20px 15px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.5);
    }

    textarea#id_description {
        width: 100%;
    }

    input#id_title {
        height: 40px;
        width: 100%;
        padding: 0 20px;
    }

    label {
        font-size: 20px;
        color: #054A91;
    }

    .form__button {
        width: 90%;
        margin: auto;
        height: 30px;
        border: none;
        background: #008BF6;
        color: white;
        cursor: pointer;
        margin-top: 10px;
        border-radius: 4px;
    }
</style>

{% extends 'base.html' %}

{% block content %}
<h1>Create Tasks</h1>

<main class="form__container">
    <form class="form" action="/tasks/create/" method="POST">
        {% csrf_token %}
        {{form}}

        <button class="form__button">
            Save
        </button>

    </form>
</main>

{% endblock %}

tasks/templates/home.html
{% extends 'base.html' %}


{% block content %}

<style>
    .container {
        max-width: 1200px;
        width: 90%;
        margin: auto;
    }

    .home {
        width: 100%;
    }

    .home__content {
        min-height: 840px;
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        max-width: 800px;
        gap: 33px;
        width: 90%;
    }

    .home__title {
        font-size: 8vw;
        text-align: center;
        color: #013D88;
    }

    .home__subtitle {
        font-size: 15px;
        text-align: center;
        color: #013D88;
    }

    .home__button {
        background-color: #008BF7;
        color: white;
        padding: 16px 36px;
        border: none;
        border-radius: 36px;
        display: inline-flex;
        font-size: 20px;
        cursor: pointer;
    }

    @media screen and (min-width: 768px) {
        .home__title {
            font-size: 60px;
        }

        .home__subtitle {
            font-size: 20px;
        }
    }

    @media screen and (min-width: 1200px) {
        .home__title {
            font-size: 70px;
        }
    }
</style>

<header class="home">
    <section class="home__content container ">
        <h1 class="home__title">Bienvenido a Soelco <br> Tu tienda Online Favorita</h1>
        <p class="home__subtitle">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat nemo, nam illo
            itaque, voluptate quam dicta nobis, odio cupiditate veniam asperiores earum minima
            !</p>


        <button class="home__button">
            Iniciar Compras
        </button>
    </section>

</header>

{% endblock %}

tasks/templates/signin.html
<style>
    .form__container {
        min-height: 900px;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }

    .form {
        max-width: 280px;
        width: 90%;
        color: black;
        background: white;
        border-radius: 12px;
        display: flex;
        flex-direction: column;
        text-align: center;
        padding: 20px 0;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.5);
    }

    .form-logo__container {
        display: flex;
        justify-content: center;
        align-items: center;
        padding: 20px 0;
    }

    .form__logo {
        max-width: 250px;
        width: 100%;
        text-align: center;
        color: black;
        display: inline-flex;
    }

    .form__paragraph {
        padding: 0 10px;
        color: #054A91;
        text-align: center;
    }

    .form-grou__container {
        display: flex;
        flex-direction: column;
        gap: 30px;
        padding-top: 30px;
    }

    .form__group {
        display: flex;
        flex-direction: column;
        width: 90%;
        margin: auto;
        text-align: left;
    }

    .form__group label {
        color: #054A91;
    }

    .form__input {
        height: 30px;
    }

    .form__button {
        width: 90%;
        margin: auto;
        height: 30px;
        border: none;
        background: #008BF6;
        color: white;
        cursor: pointer;
        border-radius: 4px;
    }
</style>

{% extends 'base.html' %}


{% block content %}
{% load static %}


<main class="form__container">
    <form class="form" action="/signin/" method="POST">
        <div class="form-logo__container">
            <img class="form__logo" src="{% static 'img/logo.png' %}" alt="logo">
        </div>

        <p class="form__paragraph">¡Bienvenido! <br> Ingresa con tu cuenta</p>
        {% csrf_token %}
        {{error}}


        <div class="form-grou__container">
            <div class="form__group">
                <label for="username">Nombre:</label>
                <input type="text" name="username" id="username" class="form__input" required>
            </div>
            <div class="form__group">
                <label for="password">Contraseña:</label>
                <input type="password" name="password" id="password" class="form__input" required>
            </div>


            <button class="form__button">
                Ingresar
            </button>
        </div>


    </form>
</main>



{% endblock %}

tasks/templates/signup.html
<style>
    .form__container {
        min-height: 900px;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }

    .form {
        max-width: 350px;
        width: 90%;
        color: black;
        background: white;
        border-radius: 12px;
        display: flex;
        flex-direction: column;
        text-align: center;
        padding: 20px 0;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.5);
    }

    .form-logo__container {
        display: flex;
        justify-content: center;
        align-items: center;
        padding: 20px 0;
    }

    .form__logo {
        max-width: 250px;
        width: 100%;
        text-align: center;
        color: black;
        display: inline-flex;
    }

    .form__paragraph {
        padding: 0 10px;
        color: #054A91;
    }

    .form-grou__container {
        display: flex;
        flex-direction: column;
        gap: 40px;
        padding-top: 30px;
    }

    .form__group {
        display: flex;
        flex-direction: column;
        width: 90%;
        margin: auto;
        text-align: left;
    }

    .form__group label {
        color: #054A91;
    }

    .form__input {
        height: 30px;
    }

    .form__button {
        width: 90%;
        margin: auto;
        height: 30px;
        border: none;
        background: #008BF6;
        color: white;
        cursor: pointer;
        border-radius: 4px;
    }
</style>

{% extends 'base.html' %}




{% block content %}
{% load static %}


<main class="form__container">
    <form class="form" action="/signup/" method="POST">
        <div class="form-logo__container">
            <img class="form__logo" src="{% static 'img/logo.png' %}" alt="logo">
        </div>

        <p class="form__paragraph">¡Bienvenido!, Te invitamos a registrarte o iniciar sesion si ya eres usuario, esto es
            necesario para
            continuar comprando</p>

        {{error}}
        {% csrf_token %}
        <!-- {{form}} -->

        <div class="form-grou__container">
            <div class="form__group">
                <label for="username">Nombre:</label>
                <input type="text" name="username" id="username" class="form__input" required>
            </div>
            <div class="form__group">
                <label for="password1">Contraseña:</label>
                <input type="password" name="password1" id="password1" class="form__input" required>
            </div>
            <div class="form__group">
                <label for="password2">Confirmar Contraseña:</label>
                <input type="password" name="password2" id="password2" class="form__input" required>
            </div>



            <button class="form__button">
                Ingresar
            </button>
        </div>

    </form>
</main>
{% endblock %}

tasks/templates/task_detail.html
<style>
    .form__container {
        min-height: 900px;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }

    .form {
        max-width: 350px;
        width: 90%;
        color: black;
        background: white;
        border-radius: 12px;
        display: flex;
        flex-direction: column;
        text-align: center;
        padding: 20px 15px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.5);
    }

    textarea#id_description {
        width: 100%;
    }

    input#id_title {
        height: 40px;
        width: 100%;
        padding: 0 20px;
    }

    label {
        font-size: 20px;
        color: #054A91;
    }

    .button__detele {
        border: none;
        text-decoration: none;
        background: #ff0000;
        padding: 10px 15px;
        color: white;
        width: 100%;
        max-width: 160px;
        text-align: center;
        cursor: pointer;
    }

    .button__complete {
        border: none;
        text-decoration: none;
        background: #1eff00;
        padding: 10px 15px;
        color: white;
        width: 100%;
        max-width: 160px;
        text-align: center;
        cursor: pointer;
    }

    .button__update {
        border: none;
        text-decoration: none;
        background: #00eeff;
        padding: 10px 15px;
        color: white;
        width: 100%;
        max-width: 160px;
        text-align: center;
        cursor: pointer;
    }
</style>

{% extends 'base.html' %}


{% block content %}
<h1>{{task.title}}</h1>

{{ error }}

<main class="form__container">
    <div class="form">
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button class="button__update">
                Update
            </button>
        </form>

        <form action="{% url 'complete_task' task.id %}" method="POST">
            {% csrf_token %}
            <button class="button__complete">
                Complete
            </button>
        </form>
        <form action="{% url 'delete_task' task.id %}" method="POST">
            {% csrf_token %}
            <button class="button__detele">
                Delete
            </button>
        </form>
    </div>
</main>

{% endblock %}

tasks/templates/tasks.html
<style>
    .lista {
        width: 100%;
    }

    .lista__content {
        width: 100%;
        padding: 50px 0;
    }

    .lista__title {
        color: #054A91;
        padding-top: 200px;
        text-align: center;
    }

    .lista__content ul {
        display: grid;
        grid-template-columns: repeat(1, 1fr);
        grid-gap: 50px;
    }

    .lista__content a {
        border: none;
        text-decoration: none;
        background: #008BF6;
        padding: 10px 15px;
        color: white;
        width: 100%;
        max-width: 160px;
        text-align: center;
    }

    .lista__content li {
        display: flex;
        flex-direction: column;
        gap: 10px;
    }



    .lista__enlace {
        color: #054A91;
    }

    .lista__description {
        color: black;
        text-align: left;
    }

    .lista__usuario {
        color: black;
    }

    @media screen and (min-width: 575px) {

        .lista__content ul {
            grid-template-columns: repeat(2, 1fr);
        }
    }

    @media screen and (min-width: 768px) {

        .lista__content ul {
            grid-template-columns: repeat(3, 1fr);
        }
    }

    @media screen and (min-width: 1200px) {

        .lista__content ul {
            grid-template-columns: repeat(4, 1fr);
        }
    }
</style>

{% extends 'base.html' %}



{% block content %}
<main class="lista">
    <div class="lista__content container">
        <ul>
            {% for task in tasks %}
            <li>

                <strong class="lista__enlace">{{task.title}}</strong>


                <p class="lista__description">{{task.description}}</p>
                <p class="lista__usuario">{{task.user.username}}</p>

                <p>{{task.datecompleted|date:'M j Y:i'}}</p>
                <a href="{% url 'task_detail' task.id %}">
                    Editar producto
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</main>

{% endblock %}